export interface VW_ProgresoCliente {
  cedula: string
  nombre_completo: string
  correo: string
  peso_registrado: number
  nivel_fitness: string
  edad_actual: number
  id_progreso: number
  fecha: string
  año: number
  mes: number
  nombre_mes: string
  periodo_legible: string
  numero_registro: string
  es_primer_registro: number
  es_ultimo_registro: number
  masa_muscular_total: number
  grasa_corporal_promedio: number
  edad_metabolica: number
  medida_promedio_cm: number
  grupos_musculares_medidos: number
  biceps_kg: number
  pectorales_kg: number
  cuadriceps_kg: number
  gluteos_kg: number
  espalda_kg: number
  abdominales_kg: number
  hombros_kg: number
  triceps_kg: number
  pantorrillas_kg: number
  isquiotibiales_kg: number
  core_kg: number
  antebrazos_kg: number
  detalles_completos: string
  logros_count: number
  objetivos_count: number
  total_detalles: number
  total_registros: number
  fecha_inicio: string
  fecha_ultimo_registro: string
  dias_total_seguimiento: number
  cambio_masa_muscular: number
  reduccion_grasa: number
  mejora_edad_metabolica: number
  progreso_masa_muscular_pct: number
  reduccion_grasa_pct: number
  mejora_edad_metabolica_pct: number
  evaluacion_constancia: string
  evaluacion_progreso_muscular: string
  entrenador_actual: string
}